image: docker

pages:
  image: node:10
  stage: deploy
  script:
    - npm config set registry http://registry.npmjs.org/
    - npm install
    - npm run build
    - mv build public
  tags:
    - docker-dind
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
    - public
  only:
    - develop
    - test
stages:
- deploy
